### ISSUE TITLE
Machine Details page not using base_domain

### ISSUE THREAD

**Issue by Gurkengewuerz** [tale/headplane#19]
The newest feature for Machine Details is using `.ts.net` hardcoded as FQDN.
It should use the user set `base_domain`.

https://github.com/tale/headplane/blob/3ea5fed8f6879af9f0aff8edc1bce1c45379ec6d/app/routes/_data.machines.%24id.tsx#L135

**Comment by tale** [comment]
Fixed in 08db192db1637e86f354e7e31fd8b093217472f1.
Available in 0.1.9
