### ISSUE TITLE
Add Node from node key

### ISSUE THREAD

**Issue by aradng** [tale/headplane#27]
Headscale-admin has an add node feature which comes handy when not using oidc or pre-auth during new machine appends to tailnet.
this with managing headscale config through headplane (similar to acl) can completely eliminate any admin intervention in cli.

also a configurable deploy tab for tailscale cli would be a nice to have :)

**Comment by tale** [comment]
Noted.

**Comment by tale** [comment]
Resolved in 0.3.2. See #22
