### ISSUE TITLE
Saving ACLs restores editor to origianal state (before editing anything)

### ISSUE THREAD

**Issue by artur9010** [tale/headplane#34]
Headscale 0.23.0, Headplane 0.3.0

[Screencast_20241001_211825.webm](https://github.com/user-attachments/assets/489ee5ed-097d-4b34-8f3c-0b55ae4bd92c)

**Comment by tale** [comment]
Thankfully not an ACL bug, it is still setting the ACL correctly and I believe if you reload the page it shows correctly. It just looks like when it refetches the ACL it gets a stale value on the frontend. I'll fix this ASAP.

**Comment by tale** [comment]
Should be resolved in 0.3.3.
