### ISSUE TITLE
ACL Documentation - ?add headscale link

### ISSUE THREAD

**Issue by arcoast** [tale/headplane#4]
I'm just getting started out with ACLs and it's great to have a link to the Tailscale webpage on this to click on easily from the headplane webui, but I wondered whether it's worthwhile to add a second link to the headscale documentation on the topic [here](https://headscale.net/acls/)?

**Comment by tale** [comment]
Fixed in 7f55ad826c6d0c372a11e78cb6b388e2f541c685. Released a docker image with 0.1.3
