### ISSUE TITLE
Unable to remove ACL tags added to node using headplane

### ISSUE THREAD

**Issue by Gerion42** [tale/headplane#41]
### Scenario
- Add tag using headplane UI
- edit tags, remove tag added
- the tag is not removed and headplane returns http 500 with the following message
```
{"message":"Failed to update tags"}
```

The headplane log only shows the request was answered with 500, no exception or anything.

**Comment by leeaash** [comment]
it seems that headplane can’t remove the last one tag

**Comment by tale** [comment]
Hmm okay, I am able to reproduce this issue, thanks for letting me know.

**Comment by stake3741** [comment]
Can confirm also. Manually resetting tags via "headscale nodes tags -i <ID>" works for now.

**Comment by tale** [comment]
Fixed in `0.3.4`
