### ISSUE TITLE
Issues opening UI

### ISSUE THREAD

**Issue by thatkid662** [tale/headplane#43]
I am trying to use this project wth my Headscale server, but I can't seem to find the home page. I keep getting 404 errors.
The only site I found to work is /admin/, which just loads forever and gives me a 302 code in the log.
Can someone kindly point out the directory where I can access the UI?

I am using advanced docker integration with a config file. No errors are in the log. 

Thanks in advance!

**Comment by tale** [comment]
What do your reverse proxy settings look like?

**Comment by thatkid662** [comment]
I'm not currently using a reverse proxy (I know, it needs one), but after I get it working I will use caddy. I am just accessing it directly, like if it was on port 8081 I would do localhost:8081.

**Comment by tale** [comment]
Did you set `COOKIE_SECURE=false` in the environment variables?

**Comment by thatkid662** [comment]
I don't think so...

**Comment by eugeneyak** [comment]
The unexpected thing for me was that you need to open localhost:8081/admin instead localhost:8081
