### ISSUE TITLE
Syntax highlighting in ACL Editor

### ISSUE THREAD

**Issue by arcoast** [tale/headplane#5]
Small syntax highlighting issue in the ACL editor I noticed, commented out ACLs are still highlighted.

![image](https://github.com/tale/headplane/assets/81871508/fade988b-ba72-49a1-b3fb-fcf05b667193)

No functional impact, but I could see it being confusing if you rely on the editor to make changes.

**Comment by tale** [comment]
Switched to Monaco, available in 0.1.9.

**Comment by arcoast** [comment]
Yep, confirmed working for me.  :+1:
