### ISSUE TITLE
[FR] Local apikeys restore support?

### ISSUE THREAD

**Issue by wx2020** [tale/headplane#51]
When i change devices to access headplane, the pages still tips me to provide new apikeys, even through i provide it on the last device.

Is it possible to store apikeys in the docker image, e.g. in an environment variable, so that headplane can be accessed via previously saved apikeys on each device?

Hope your reply.

**Comment by tale** [comment]
I'm confused what you mean, can you explain better?

**Comment by tale** [comment]
But that's an authentication mechanism. That would be like saving your login information.
