### ISSUE TITLE
Feature Request: Add "Copy to Clipboard" Button for Registration Command in "Register Machine Key" Modal

### ISSUE THREAD

**Issue by 2TAP2B** [tale/headplane#52]
**Description**

When adding a new machine and opening the "Register Machine Key" modal (accessible via Add Machine > Register Machine Key), it would be extremely helpful to have a "Copy to Clipboard" button for the `tailscale up --login-server=https://headscale.server.com `command. 

This functionality is already available on the "Machines" page for the IP address, and implementing it here would improve usability by making it quicker and easier to copy the full command for new machine registration.

**Requested Feature**

Add a Copy to Clipboard button next to the `tailscale up --login-server=https://headscale.server.com` command in the "Register Machine Key" modal.
Benefit

**This feature would:**
* Simplify the process of copying the registration command.
* Improve user experience and reduce the chance of manual copying errors.

**Comment by tale** [comment]
Will do!

**Comment by tale** [comment]
Added a copy button next to the actual display in `0.3.6`

**Comment by 2TAP2B** [comment]
when copy via clicking the icon something goes wrong. this is what is in my clipboard, there is a "," behind the = 

`tailscale up --login-server=,https://headscale.server.com`

**Comment by tale** [comment]
Will fix this within the next release, my fault.

**Comment by tale** [comment]
Fixed in `0.3.7`.
