### ISSUE TITLE
[Bug] User select can't scroll

### ISSUE THREAD

**Issue by itfsw** [tale/headplane#53]
version: 0.3.5
bug: user select panel can't scroll when we have many users.
![微信截图_20241118100458](https://github.com/user-attachments/assets/85878b47-c249-423d-b6d4-f63d229cca14)
where:
1. Register Machine Key
2. Change the owner
3. Generate auth key
4. Pre-Auth Keys

**Comment by tale** [comment]
Fixed in `0.3.6`
