### ISSUE TITLE
Allow key expirations higher than 90 days

### ISSUE THREAD

**Issue by Silex** [tale/headplane#58]
For automation I need long lasting (99y) preauth keys and it's annoying having to go to the console for that.

**Comment by tale** [comment]
I'm unsure if the API even supports this.

**Comment by tale** [comment]
Oh wait, if the CLI supports it the API should, let me look into it.

**Comment by Silex** [comment]
Yeah you can use `-e 99y` in the CLI.

**Comment by robsiera** [comment]
yes, d(ays), h(ours), w(eeks) are also supported, so I'm told.

**Comment by tale** [comment]
![CleanShot 2024-12-06 at 18 35 37@2x](https://github.com/user-attachments/assets/71e59d50-ca49-43c0-b816-cb75a5e93522)

This has been implemented, but to preserve the UX I kept it in days. Just tested and generated a key that lasts 365,000 days (1000 years).

**Comment by tale** [comment]
Live in `0.3.9`!
