### ISSUE TITLE
Add a /health endpoint

### ISSUE THREAD

**Issue by rgarrigue** [tale/headplane#59]
Hello

I'd like to be able to call a /health to know if everything is alright at a glance, like for headscale

![image](https://github.com/user-attachments/assets/d1dbba4a-857c-4bf1-9cd4-bec1282f405b)

It could return 500 if unable to contact headscale & 200 otherwise. Must be without auth, since those are often used by monitoring or kubernetes to check if everything's alright.

Thanks !

**Comment by tale** [comment]
Added in `0.3.7`, it will be under `/admin/healthz`.
