### ISSUE TITLE
Wrong Headscale URL in the machine registration command

### ISSUE THREAD

**Issue by gjirm** [tale/headplane#60]
Hello, I have a headscale and headplane containers in Docker behind the proxy beacuse of that I changed `HEADSCALE_URL` env config to  `http://headscale:8080` so headplane can connect to headscale container via Dokcer network.

But now my machine registration command contains this local  `--login-server=http://headscale:8080` insted of public Headscale URL configured in the Headscale config.

![image](https://github.com/user-attachments/assets/436cb749-913a-4a32-ae1d-f40149219046)

Would it be possible to change this registration login URL to that in the main Headscale config?

**Comment by tale** [comment]
Because of how the configuration is read, the environment variables always have precedence over the configuration file. I could also split it off into a `HEADSCALE_PUBLIC_URL` variable, that if set will be used for these kinds of things.

**Comment by gjirm** [comment]
> Because of how the configuration is read, the environment variables always have precedence over the configuration file. I could also split it off into a `HEADSCALE_PUBLIC_URL` variable, that if set will be used for these kinds of things.

Okay, I understand. I think this solution you're suggesting is ok.

**Comment by tale** [comment]
This is customizable in `0.3.7`
