### ISSUE TITLE
Feature request - Display the headplane version number somewhere

### ISSUE THREAD

**Issue by Drizztfire** [tale/headplane#62]
Hi,

Thanks for your great work !!!

This should be a simple feature to implement ...
I was looking for the running version the other day and couldn't fint it anywhere ... 

Not a big issue, but a nice quality of life feature

Thanks

**Comment by tale** [comment]
Gotcha, I just committed it and it will be there in the next release!

**Comment by Drizztfire** [comment]
Awesome !!!
Thanks

**Comment by tale** [comment]
Live in `0.3.9`!
