### ISSUE TITLE
Clarification on Restricting Admin Rights in Headplane UI

### ISSUE THREAD

**Issue by 2TAP2B** [tale/headplane#64]
The ACL configuration in test/acl.json works perfectly for controlling network access, such as accepting or declining SSH connections. However, I noticed a potential gap in restricting user permissions in the Headplane UI.

**In my setup, I have two user groups:**

- Admin: Full access to all resources.
- User: Limited access to only their own machine as defined in the ACL.

While the ACL ensures proper network access control, I realized that users in the "User" group can still make changes in the Headplane UI, such as editing the ACL. This effectively grants them administrative capabilities, which undermines the intention of having limited user roles.

**What I’m Missing?**

Is there a way to enforce role-based permissions in the Headplane UI to ensure:

- Only admins can modify the ACL or perform administrative tasks in the UI?
- Non-admin users are restricted to only viewing their assigned resources and cannot make any changes to the system configuration?

It seems like this aspect of permissions management is outside the scope of the ACL file itself. If so, could you clarify:

- Whether this is a feature planned for future releases?
- Or if there's an existing configuration that I might be missing?

**Comment by tale** [comment]
There currently are not permissions, this is something I'm looking to resolve within the next couple versions.

**Comment by tale** [comment]
See #18. https://github.com/tale/headplane/issues/18#issuecomment-2526363494
